#!/usr/bin/env python3

import sys
import argparse
import __init__ as workflow

from pathlib import Path

import datetime

parser = argparse.ArgumentParser()
parser.add_argument("--path", help="Path to folder on disk to store certs", type=Path)
parser.add_argument(
    "--filter-bucket", help="Google Cloud Storage filter bucket name", required=True
)

args = parser.parse_args()

if not args.path:
    parser.print_usage()
    sys.exit(0)

now = datetime.datetime.now(datetime.UTC)
dateprefix = now.strftime("%Y%m%d")
next_idx = 0

all_identifiers = workflow.get_run_identifiers(args.filter_bucket)
if all_identifiers:
    most_recent_identifier = all_identifiers.pop()
    (date_part, idx_part) = most_recent_identifier.split("-")
    if date_part == dateprefix:
        next_idx = int(idx_part) + 1

allocatedName = "{}-{}".format(dateprefix, next_idx)
allocatedPath = args.path / Path(allocatedName)

allocatedPath.mkdir()

timestamp_file = allocatedPath / Path("timestamp")
timestamp_file.write_text(now.isoformat(timespec="seconds"), encoding="utf-8")

print(allocatedPath)
