#!/bin/bash

remaining="$(pgrep --exact ct-fetch)"
if [ "${remaining}" != "" ] ; then
  echo "Stopping other instances of ct-fetch at these PIDs: ${remaining}"
  # cleanly stop all ct-fetch ops running
  killall --exact --wait -SIGTERM ct-fetch

  sleep 3
fi

remaining="$(pgrep --exact ct-fetch)"
if [ "${remaining}" != "" ] ; then
  echo "WARNING: There may still be running ct-fetch instances at these PIDs: ${remaining}"
fi


cmd="${crlite_bin:-~/go/bin}/ct-fetch -log_dir ${crlite_log:-/tmp}/ -stderrthreshold=WARNING"
env

echo "Starting ${cmd}..."
echo "Expect ${outputRefreshPeriod} lag for initial output."

if [ -x /usr/bin/time ] ; then
  /usr/bin/time ${cmd}
else
  ${cmd}
fi
