#!/bin/bash

if [ $# -ne 1 ] ; then
  echo "Usage: $0 /ct/processing/{IDENTIFIER}"
  exit 1
fi

if [ ! -d ${1} ] ; then
  echo "Not a directory: ${1}"
  exit 1
fi

${crlite_bin:-~/go/bin}/aggregate-known -outpath ${1}/known -log_dir ${crlite_log:-/tmp}
