#!/bin/bash

if [ $# -ne 1 ] ; then
  echo "Usage: $0 /ct/processing/{IDENTIFIER}"
  exit 1
fi

WORKDIR="${1}"

if [ ! -d ${WORKDIR} ] ; then
  echo "Not a directory: ${WORKDIR}"
  exit 1
fi

if [ ! -d ${WORKDIR}/log ] ; then
  mkdir ${WORKDIR}/log
fi

if [ ! -r ${crlite_processing:-/ct}/ccadb-intermediates.csv ] ; then
  curl https://ccadb-public.secure.force.com/mozilla/MozillaIntermediateCertsCSVReport \
        --output ${crlite_processing:-/ct}/ccadb-intermediates.csv
fi

${crlite_bin:-~/go/bin}/aggregate-known -knownpath ${WORKDIR}/known \
              -enrolledpath ${WORKDIR}/enrolled.json \
              -stderrthreshold=WARNING -log_dir ${WORKDIR}/log
