#!/bin/bash

export HTTPS_PROXY=socks5://localhost:32547/ 

validateMLBF() {
  mlbf="${1}"
  if [ ! -r "${mlbf}" ] ; then
    echo "MLBF not found at ${mlbf}"
    exit 1
  fi

  if [ ! -r "${mlbf}.meta" ] ; then
    echo "MLBF metadata not found at ${mlbf}.meta"
    exit 1
  fi
}

if [ "$KINTO_AUTH_USER" == "" ] ; then
  echo "You'll need to export or set KINTO_AUTH_USER and KINTO_AUTH_PASSWORD before calling this."
  echo "Example: "
  echo "   KINTO_AUTH_PASSWORD=password KINTO_AUTH_USER=username $0"
  exit 1
fi

if [ $# -lt 1 ] ; then
   echo "Usage: $0 /ct/processing/{IDENTIFIER}"
   exit 1
fi

if [ ! -d ${1} ] ; then
  echo "${1} is not a path."
  exit 1
fi

force=0
if [ $# -gt 1 ] ; then
  echo "Forcing a complete file"
  force=1
fi

identifier="$(basename ${1})"
currentMLBF="/ct/processing/${identifier}/mlbf/filter"
validateMLBF "${currentMLBF}"

previousIdentifier=$(basename $(find /ct/processing -maxdepth 1 -type d | grep -v "${identifier}" | tail -n 1))
previousMLBF="/ct/processing/${previousIdentifier}/mlbf/filter"
validateMLBF "${previousMLBF}"

patchMLBF="$(ls /ct/processing/${identifier}/mlbf/filter*patch | head -n1)"

ls -la "${patchMLBF}" "${currentMLBF}"

filterSize=$(stat --printf="%s" "${currentMLBF}")
patchSize=$(stat --printf="%s" "${patchMLBF}")
ratio=$(echo ${patchSize}/${filterSize} | bc -l)

if [[ ${force} -gt 0 ]] ; then
  ratio=2
fi

echo "Filter size: ${filterSize}"
echo "Patch size: ${patchSize}"
echo "Ratio: ${ratio}"


echo "Auth token: $KINTO_AUTH_TOKEN"
echo "Proxy: $HTTPS_PROXY"
echo "Remember, you needed to SSH into here with 'ssh -R 32547 <hostname>' to set up the reverse proxy. "
echo "Also note:"
echo "  1) This is a cheating way to get around firewall restrictions, bouncing to your home box."
echo "  2) You'll need to have the VPN connected."
echo "  3) You'll need OpenSSH 6.7 or later."

if (( $(echo "${ratio} > 0.4" | bc -l) )) ; then
  echo "Making a new base filter."
  python3 ~/crlite/kinto-publisher/main.py --crlite --in "${currentMLBF}"

else
  echo "Posting a new incremental filter patch."
  python3 ~/crlite/kinto-publisher/main.py --crlite --diff --in "${patchMLBF}"
fi

