#!/usr/bin/env python3

from datetime import datetime, timezone
import argparse
import progressbar
from google.cloud import firestore

parser = argparse.ArgumentParser()
parser.add_argument(
    "--noop", "-n", help="Don't actually delete, just print", action="store_true"
)
parser.add_argument("--today", help="Today's date YYYY-MM-DD-HH")


def main():
    args = parser.parse_args()

    if args.noop:
        print("No-op mode, not deleting anything...")

    now = datetime.now(timezone.utc)
    if args.today:
        now = datetime.strptime(args.today, "%Y-%m-%d-%H")

    expDate = now.strftime("%Y-%m-%d-%H")
    print(f"Expiration date: {expDate}")

    db = firestore.Client()
    expDateList = list(db.collection("ct").where("expDate", "<", expDate).stream())

    for docSnap in progressbar.progressbar(expDateList):
        print(f"Deleting {docSnap.id}")
        if args.noop:
            continue

    print("All done.")


if __name__ == "__main__":
    main()
