#!/usr/bin/env python3

from google.cloud import storage

import argparse
import os
import sys

parser = argparse.ArgumentParser()
parser.add_argument("--path", help="Path to folder to upload")


def main():
    args = parser.parse_args()

    if not args.path:
        parser.print_usage()
        sys.exit(0)

    storage_client = storage.Client()
    bucket_name = 'crlite_filters'
    bucket = storage_client.get_bucket(bucket_name)

    if args.path.endswith("/"):
        args.path = args.path[:len(args.path)-1]
    idName = os.path.basename(args.path)

    for path, dirs, files in os.walk(args.path):
        for item in files:
            print(f"Uploading {path}/{item} as {idName}/{item}")
            blob = bucket.blob(os.path.join(idName, item))
            blob.upload_from_filename(os.path.join(path, item))


main()
