#!/usr/bin/env python3

from google.cloud import storage
from pathlib import Path

import argparse
import os
import sys

parser = argparse.ArgumentParser()
parser.add_argument("identifier", help="Path to folder to upload", nargs=1)


def main():
    args = parser.parse_args()

    if not args.identifier or len(args.identifier) != 1:
        parser.print_usage()
        sys.exit(0)

    storage_client = storage.Client()
    bucket_name = 'crlite_filters'
    bucket = storage_client.get_bucket(bucket_name)

    idPath = Path(args.identifier[0]).resolve()

    for path, dirs, files in os.walk(idPath):
        localFolder = Path(path)
        remoteFolder = localFolder.relative_to(idPath.parent)

        for item in files:
            localFilePath = localFolder.joinpath(item)
            remoteFilePath = remoteFolder.joinpath(item)

            print(f"Uploading {remoteFilePath} (size={localFilePath.stat().st_size}) "
                  + f"from {localFilePath}")
            blob = bucket.blob(str(remoteFilePath))
            blob.upload_from_filename(str(localFilePath))


main()
