repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: HEAD
  hooks:
    - id: go-fmt
    - id: validate-toml
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: HEAD
  hooks:
    - id: check-ast
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: https://gitlab.com/pycqa/flake8
  rev: HEAD
  hooks:
    - id: flake8
- repo: local
  hooks:
    - id: pytest
      name: Python Tests
      language: system
      entry: python3 -m pytest
      pass_filenames: false
      files: '.py$'
- repo:  git://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
