- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-fmt
    - id: validate-toml
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: HEAD
  hooks:
    - id: flake8
    - id: check-ast
    - id: detect-private-key
    - id: detect-aws-credentials
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: go-unit-tests
      name: Go unit tests
      language: script
      entry: hooks/go-unit-tests.sh
      files: '\.go$'
    - id: go-no-replacement
      name: Avoid committing a go module replacement
      entry: ./hooks/go-no-replacement.sh
      language: script
      files: go.mod
    - id: create-filter-cascade-tests
      name: Tests for create-filter-cascade
      language: system
      entry: python3 -m unittest create_filter_cascade/test.py
      pass_filenames: false
      files: '.py$'
