steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}', '.',
          '-f', './containers/Dockerfile',
          '--build-arg', 'ct_mapreduce_ver=${_CT_MAPREDUCE_VERSION}' ]
  id: 'crlite'

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}-fetch', '.',
          '-f', './containers/crlite-fetch/Dockerfile',
          '--build-arg', 'crlite_image=gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}' ]
  wait_for: ['crlite']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}-generate', '.',
          '-f', './containers/crlite-generate/Dockerfile',
          '--build-arg', 'crlite_image=gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}' ]
  wait_for: ['crlite']

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}-publish', '.',
          '-f', './containers/crlite-publish/Dockerfile',
          '--build-arg', 'crlite_image=gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}' ]
  wait_for: ['crlite']

substitutions:
    _CRLITE_TAG: "staging"
    _CT_MAPREDUCE_VERSION: "v1.0.6"

images:
- 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}'
- 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}-fetch'
- 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}-generate'
- 'gcr.io/$PROJECT_ID/crlite:${_CRLITE_TAG}-publish'
