apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: crlite-publish
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: crlite-publish
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: crlite-publish
            envFrom:
            - configMapRef:
                name: crlite-config
            image: gcr.io/crlite-beta/crlite:0.1-publish
            imagePullPolicy: Always
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: FallbackToLogsOnError
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
