#!/bin/bash -xe

workflow=~/go/src/github.com/mozilla/crlite/workflow

# TODO: renumber
${workflow}/6-cleanup-expired-ct-folders
${workflow}/7-cleanup-expired-processing-folders

ID=$(${workflow}/0-allocate_identifier)

${workflow}/1-ct-fetch
${workflow}/2-produce_revocation_data ${ID}
${workflow}/3-produce_known_data ${ID}
${workflow}/4-generate_mlbf ${ID}

