#!/bin/bash -xe

workflow=${crlite_workflow:-~/go/src/github.com/mozilla/crlite/workflow}

# TODO: renumber
${workflow}/6-cleanup-expired-ct-folders --path ${crlite_ctdata:-/ct}
${workflow}/7-cleanup-expired-processing-folders --path ${crlite_processing:-/ct/processing}

ID=$(${workflow}/0-allocate_identifier --path ${crlite_processing:-/ct/processing/})

${workflow}/1-ct-fetch
${workflow}/2-produce_revocation_data ${ID}
${workflow}/3-produce_known_data ${ID}
${workflow}/4-generate_mlbf ${ID}
${workflow}/5-upload_intermediates ${ID}
