#!/bin/bash -e

if [ "x${credentials_data}x" != "xx" ] ; then
  echo "GOT ME SOME credentials_data FOR GOOGLE_APPLICATION_CREDENTIALS"
  echo "${credentials_data}" | base64 --decode >> /tmp/credentials.json
  export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json
fi

workflow=${crlite_workflow:-~/go/src/github.com/mozilla/crlite/workflow}

# TODO: renumber
# TODO: port to firestore
#${workflow}/6-cleanup-expired-ct-folders --path ${crlite_ctdata:-/ct}

if [ "x${reprocess_certs}x" == "xtruex" ]; then
  ${workflow}/0-reprocess_certs
elif [ "x${fetch_certs}x" == "xtruex" ]; then
  ${workflow}/1-ct-fetch
else
  ID=$(${workflow}/0-allocate_identifier --path ${crlite_processing:-/ct/processing/})
  echo "Allocated ${ID}"

  ${workflow}/2-produce_revocation_data ${ID}
  ${workflow}/3-produce_known_data ${ID}
  ${workflow}/4-generate_mlbf ${ID}
  ${workflow}/8-upload_artifacts_to_storage ${ID}

  ${workflow}/7-cleanup-expired-processing-folders --path ${crlite_processing:-/ct/processing}

  if [ "x${KINTO_AUTH_USER}x" == "xx" ]; then
    echo "KINTO_AUTH_USER not set, exiting before the kinto-operations"
    exit 0
  fi

  ${workflow}/5-upload_intermediates ${ID}
  ${workflow}/5-upload_mlbf_to_kinto ${ID}
fi
