#!/bin/bash -e

if [ "x${credentials_data}x" != "xx" ] ; then
  echo "GOT ME SOME credentials_data FOR GOOGLE_APPLICATION_CREDENTIALS"
  echo "${credentials_data}" | base64 --decode >> /tmp/credentials.json
  export GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json
fi

workflow=${crlite_workflow:-~/go/src/github.com/mozilla/crlite/workflow}

# TODO: renumber
# TODO: port to firestore
#${workflow}/6-cleanup-expired-ct-folders --path ${crlite_ctdata:-/ct}
#${workflow}/7-cleanup-expired-processing-folders --path ${crlite_processing:-/ct/processing}

ID=$(${workflow}/0-allocate_identifier --path ${crlite_processing:-/ct/processing/})

if [ "x${reprocess_certs}x" != "xx" ]; then
  ${workflow}/0-reprocess_certs
fi

${workflow}/1-ct-fetch
${workflow}/2-produce_revocation_data ${ID}
${workflow}/3-produce_known_data ${ID}
${workflow}/4-generate_mlbf ${ID}
${workflow}/5-upload_intermediates ${ID}
