apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: crlite-fetch
  name: crlite-fetch
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: crlite-fetch
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crlite-fetch
    spec:
      containers:
      - name: crlite-fetch
        image: docker.io/mozilla/crlite:latest-fetch
        envFrom:
        - configMapRef:
            name: crlite-config
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 8080
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 60
          periodSeconds: 60
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
status:
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
